spring:
    datasource:
      url: jdbc:postgresql://ep-broad-hat-adixmbvj-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: create-drop
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

    mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    debug: true
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          ssl:
            enable: true


app:
  email: ${MAIL_USERNAME}
  baseUrl: http://localhost:8081


server.port: 8081